In [1]:
import os
os.getcwd() #To get the current working directory

'C:\\Users\\mounika\\Desktop\\SMS Spam Detection'

In [2]:
os.chdir("C:/Users/mounika/Desktop/internship_project") #To change the directory
os.getcwd()

'C:\\Users\\mounika\\Desktop\\internship_project'

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset 

In [4]:
dataset = pd.read_csv("spam.csv", encoding='latin-1')
dataset.dropna(how="any", inplace=True, axis=1)
dataset.columns = ['label', 'message']
dataset

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Cleaning or pre-processing

In [5]:
#Library to clean the text
import re

#Natural language toolkit library
import nltk

#library used to remove stopwords
nltk.download('stopwords')
from nltk.corpus import stopwords

#Library used for stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()  #creating an object for stemming
data=[]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mounika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
#Applying for all rows
for i in range(0,5572):
        message=dataset["message"][i]
        
        #replacing punctuations and numbers
        message = re.sub('[^a-zA-Z]', ' ',message)
       
        #convert each word into lower case
        message = message.lower()  
        
        message = message.split()
        
        #apply stemming
        message = [ps.stem(word) for word in message if not word in set(stopwords.words('english'))]
        
        message = ' '.join(message)
        data.append(message)

In [7]:
dataset['label'].replace(['ham','spam'],[0,1],inplace=True)

In [8]:
        
from sklearn.feature_extraction.text import CountVectorizer #for bag of words
cv = CountVectorizer(max_features=100) 
X = cv.fit_transform(data).toarray() #convert into matrix form
y=dataset.iloc[:,0].values 
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

# Splitting the dataset into train and test

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [10]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
import pickle
pickle.dump(cv, open("cv.pkl", "wb"))

# Importing the libraries which uses tensorflow as backend

In [15]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [16]:
#Initializing the model
model = Sequential()


#adding input layer
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 100))

#adding hidden layers
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))


#Adding output layer
model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))


C:\Users\mounika\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=100, units=8, kernel_initializer="uniform")`
  
C:\Users\mounika\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\mounika\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\mounika\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\mounika\Anaconda3\lib\site-packages\ipykernel_launcher

In [17]:
#compiling the model
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [18]:
#Training the model
model.fit(X_train,y_train,batch_size=50,epochs=32)


Epoch 1/32
4457/4457 [==============================] - 1s 310us/step - loss: 0.6774 - accuracy: 0.8696
Epoch 2/32
4457/4457 [==============================] - 0s 66us/step - loss: 0.6470 - accuracy: 0.8696
Epoch 3/32
4457/4457 [==============================] - 0s 63us/step - loss: 0.6193 - accuracy: 0.8696
Epoch 4/32
4457/4457 [==============================] - 0s 60us/step - loss: 0.5943 - accuracy: 0.8696
Epoch 5/32
4457/4457 [==============================] - 0s 63us/step - loss: 0.5716 - accuracy: 0.8696
Epoch 6/32
4457/4457 [==============================] - 0s 56us/step - loss: 0.5512 - accuracy: 0.8696
Epoch 7/32
4457/4457 [==============================] - 0s 63us/step - loss: 0.5329 - accuracy: 0.8696
Epoch 8/32
4457/4457 [==============================] - 0s 79us/step - loss: 0.5164 - accuracy: 0.8696
Epoch 9/32
4457/4457 [==============================] - 0s 68us/step - loss: 0.5015 - accuracy: 0.8696
Epoch 10/32
4457/4457 [==============================] - 0s 54us/step -

# Save the model


In [19]:
model.save('mymodel.h5')