In [1]:
import os
os.getcwd() #To get the current working directory

'C:\\Users\\HP\\OneDrive\\Desktop\\internship_project'

In [2]:
os.chdir("C:/Users/HP/OneDrive/Desktop/internship_project") #To change the directory
os.getcwd()

'C:\\Users\\HP\\OneDrive\\Desktop\\internship_project'

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset 

In [4]:
dataset = pd.read_csv("spam.csv", encoding='latin-1')
dataset.dropna(how="any", inplace=True, axis=1)
dataset.columns = ['label', 'message']
dataset

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Cleaning or pre-processing

In [5]:
#Library to clean the text
import re

#Natural language toolkit library
import nltk

#library used to remove stopwords
nltk.download('stopwords')
from nltk.corpus import stopwords

#Library used for stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()  #creating an object for stemming
data=[]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
#Applying for all rows
for i in range(0,5572):
        message=dataset["message"][i]
        
        #replacing punctuations and numbers
        message = re.sub('[^a-zA-Z]', ' ',message)
       
        #convert each word into lower case
        message = message.lower()  
        
        message = message.split()
        
        #apply stemming
        message = [ps.stem(word) for word in message if not word in set(stopwords.words('english'))]
        
        message = ' '.join(message)
        data.append(message)

In [7]:
dataset['label'].replace(['ham','spam'],[0,1],inplace=True)

In [8]:
        
from sklearn.feature_extraction.text import CountVectorizer #for bag of words
cv = CountVectorizer(max_features=100) 
X = cv.fit_transform(data).toarray() #convert into matrix form
y=dataset.iloc[:,0].values 
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

# Splitting the dataset into train and test

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [10]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: Future

In [15]:
#Initializing the model
model = Sequential()


#adding input layer
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 100))

#adding hidden layers
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))


#Adding output layer
model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))


C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=100, units=8, kernel_initializer="uniform")`
  
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Upda

In [16]:
#compiling the model
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [17]:
#Training the model
model.fit(X_train,y_train,batch_size=50,epochs=32)


Epoch 1/32
4457/4457 [==============================] - 1s 230us/step - loss: 0.6646 - acc: 0.8696
Epoch 2/32
4457/4457 [==============================] - 0s 36us/step - loss: 0.4866 - acc: 0.8696
Epoch 3/32
4457/4457 [==============================] - 0s 38us/step - loss: 0.3364 - acc: 0.8696
Epoch 4/32
4457/4457 [==============================] - 0s 35us/step - loss: 0.2166 - acc: 0.8696
Epoch 5/32
4457/4457 [==============================] - 0s 34us/step - loss: 0.1688 - acc: 0.8696
Epoch 6/32
4457/4457 [==============================] - 0s 32us/step - loss: 0.1595 - acc: 0.8696
Epoch 7/32
4457/4457 [==============================] - 0s 33us/step - loss: 0.1537 - acc: 0.8696
Epoch 8/32
4457/4457 [==============================] - 0s 32us/step - loss: 0.1496 - acc: 0.9107
Epoch 9/32
4457/4457 [==============================] - 0s 35us/step - loss: 0.1467 - acc: 0.9715
Epoch 10/32
4457/4457 [==============================] - 0s 33us/step - loss: 0.1447 - acc: 0.9729
Epoch 11/32
4457/

# Save the model

In [18]:
model.save('mymodel.h5')

# Predictions

In [19]:
r=model.predict(cv.transform(['hey hi how are you']))
r

array([[0.00497784]], dtype=float32)

In [20]:
r=model.predict(cv.transform(['URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18']))
r

array([[0.73037136]], dtype=float32)

In [21]:
r=model.predict(cv.transform(['Is that seriously how you spell his name?']))
r

array([[0.01488547]], dtype=float32)

In [22]:
y_pred=model.predict(X_test)

In [23]:
y_pred

array([[3.4511089e-05],
       [1.4885455e-02],
       [7.3644519e-04],
       ...,
       [4.3886327e-03],
       [3.3148441e-05],
       [1.2253165e-03]], dtype=float32)

In [24]:
y_pred=(y_pred>0.5)

In [25]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [26]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
m=confusion_matrix(y_test,y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9596412556053812